FROM alpine

RUN apk update && apk add wget openssl supervisor nginx php7 php7-cli php7-cgi php7-mbstring php7-fpm php7-mcrypt php7-soap php7-openssl php7-gmp php7-pdo_odbc php7-json php7-dom php7-pdo php7-zip php7-mysqli php7-sqlite3 php7-apcu php7-pdo_pgsql php7-bcmath php7-gd php7-odbc php7-pdo_mysql php7-pdo_sqlite php7-gettext php7-xmlreader php7-xmlrpc php7-bz2 php7-iconv php7-pdo_dblib php7-curl php7-ctype php7-common php7-xml php7-imap fcgi php7-posix php7-ldap php7-session --no-cache && apk add telegraf --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted --no-cache

COPY ssl_key_crt_gen.sh /ssl_key_crt_gen.sh
